on:
    workflow_dispatch:
    push:
      branches:
        - main
jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: aws-actions/setup-sam@v2
          with:
            use-installer: true
            token: ${{ secrets.GITHUB_TOKEN }}
        - uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-2
        - name: Set region in samconfig.toml
          run: sed -i 's/AWS_REGION/${{ secrets.AWS_REGION }}/g' samconfig.toml
        # Build inside Docker containers
        - run: sam build
        # Prevent prompts and failure when the stack is unchanged
        - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
